# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Painel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_painel(object):
    def setupUi(self, painel):
        painel.setObjectName("painel")
        painel.resize(1352, 739)
        self.centralwidget = QtWidgets.QWidget(painel)
        self.centralwidget.setObjectName("centralwidget")
        self.Velocimetro = QtWidgets.QWidget(self.centralwidget)
        self.Velocimetro.setGeometry(QtCore.QRect(0, 0, 691, 421))
        self.Velocimetro.setObjectName("Velocimetro")
        self.RPM = QtWidgets.QWidget(self.centralwidget)
        self.RPM.setGeometry(QtCore.QRect(689, 0, 661, 421))
        self.RPM.setObjectName("RPM")
        self.Bateria = QtWidgets.QWidget(self.centralwidget)
        self.Bateria.setGeometry(QtCore.QRect(520, 420, 361, 251))
        self.Bateria.setObjectName("Bateria")
        self.Temperatura = QtWidgets.QWidget(self.centralwidget)
        self.Temperatura.setGeometry(QtCore.QRect(880, 420, 311, 251))
        self.Temperatura.setObjectName("Temperatura")
        self.Temperatura_freio = QtWidgets.QWidget(self.centralwidget)
        self.Temperatura_freio.setGeometry(QtCore.QRect(260, 420, 261, 251))
        self.Temperatura_freio.setObjectName("Temperatura_freio")
        painel.setCentralWidget(self.centralwidget)

        self.retranslateUi(painel)
        QtCore.QMetaObject.connectSlotsByName(painel)

    def retranslateUi(self, painel):
        _translate = QtCore.QCoreApplication.translate
        painel.setWindowTitle(_translate("painel", "MainWindow"))
